apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: myacr321012999999.azurecr.io/spring-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2000
# service type loadbalancer       
---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: spring-app
#     k8s-app: spring-app
#   name: spring-app
# spec:
#   ports:
#   - name: http
#     port: 80
#     protocol: TCP
#     targetPort: 2000
#   type: LoadBalancer
#   selector:
#     app: spring-app
