apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      - name: react-app
        image: yassinemaadane/react-app
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
# service type loadbalancer       
---
 apiVersion: v1
 kind: Service
 metadata:
   labels:
     app: spring-app
     k8s-app: spring-app
   name: spring-app
 spec:
   ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 3000
   type: LoadBalancer
   selector:
     app: spring-app
